<?php
namespace OpenEMR\Modules\NeoLimsBridge\Service;
use OpenEMR\Common\Uuid\UuidRegistry;
use OpenEMR\Modules\NeoLimsBridge\GlobalConfig;
use OpenEMR\Modules\NeoLimsBridge\Repository\DocumentLinkRepository;
use OpenEMR\Modules\NeoLimsBridge\Repository\ResultLinkRepository;
use OpenEMR\Services\DocumentService;
final class DocumentSyncService
{
    private DocumentLinkRepository $links; private ResultLinkRepository $reports; private GlobalConfig $config;
    public function __construct(){ $this->links=new DocumentLinkRepository();$this->reports=new ResultLinkRepository();$this->config=new GlobalConfig($GLOBALS); }
    public function validate(array $r): array { $n=$this->normalize($r);$e=[];$report=$this->reports->find($n['connection_key'],$n['local_report_id']);if(!$report)$e[]='Permanent result/report link not found.';$content=base64_decode($n['content_base64'],true);if($content===false||$content==='')$e[]='content_base64 is invalid or empty.';if(strlen((string)$content)>$n['max_bytes'])$e[]='Document exceeds maximum allowed size.';$ds=new DocumentService();if(!$ds->isValidPath($n['category_path']))$e[]='OpenEMR document category path does not exist.';$existing=$this->links->find($n['connection_key'],$n['local_document_id']);$hash=$content===false?'':hash('sha256',$content);return ['valid'=>$e===[],'errors'=>$e,'normalized'=>$n,'report_link'=>$report,'existing_document_link'=>$existing,'content_hash'=>$hash,'can_create'=>$e===[]&&!$existing]; }
    public function sync(array $r): array { $v=$this->validate($r);if(!$v['valid'])return $v+['written'=>false];if($v['existing_document_link']&&hash_equals((string)$v['existing_document_link']['content_hash'],$v['content_hash']))return ['resolution'=>'unchanged','created'=>false,'written'=>false,'document'=>$this->links->document((int)$v['existing_document_link']['openemr_document_id'])];if(!empty($r['dry_run']))return $v+['written'=>false,'dry_run'=>true];if(!$this->config->enabled(GlobalConfig::ENABLE_NATIVE_WRITES))throw new \InvalidArgumentException('Native writes are disabled; use dry_run=true or enable the module setting.');if($v['existing_document_link'])throw new \InvalidArgumentException('Existing document content differs. Create a new local_document_id for an amendment.');$n=$v['normalized'];$report=$v['report_link'];$reportRow=$this->reports->getReport((int)$report['openemr_report_id']);$order=sqlQuery('SELECT patient_id,encounter_id FROM procedure_order WHERE procedure_order_id=?',[(int)$report['openemr_order_id']]);if(!$order)throw new \RuntimeException('Linked procedure order not found.');$content=base64_decode($n['content_base64'],true);$ds=new DocumentService();$cat=(int)$ds->getLastIdOfPath($n['category_path']);$doc=new \Document();$owner=(int)($_SESSION['authUserID']??0);$err=$doc->createDocument((int)$order['patient_id'],$cat,$n['filename'],$n['mimetype'],$content,'',1,$owner,null,null,(int)$report['openemr_report_id'],'procedure_report',(int)$order['encounter_id']);if($err!=='')throw new \RuntimeException((string)$err);$id=(int)$doc->get_id();if($id<=0)throw new \RuntimeException('OpenEMR did not return the new document ID.');sqlStatement('UPDATE documents SET encounter_id=?,docdate=? WHERE id=?',[(int)$order['encounter_id'],$n['document_date'],$id]);$uuid=UuidRegistry::uuidToString($doc->get_uuid());$i=$n['identifier'];$this->links->save(['connection_key'=>$n['connection_key'],'local_document_id'=>$n['local_document_id'],'local_report_id'=>$n['local_report_id'],'openemr_document_id'=>$id,'openemr_document_uuid'=>$uuid,'openemr_report_id'=>(int)$report['openemr_report_id'],'openemr_pid'=>(int)$order['patient_id'],'filename'=>$n['filename'],'mimetype'=>$n['mimetype'],'content_hash'=>$v['content_hash'],'external_identifier_system'=>$i['system'],'external_identifier_value'=>$i['value']]);return ['resolution'=>'created','created'=>true,'written'=>true,'document'=>$this->links->document($id)]; }
    public function fromFhir(array $f,?string $uuid=null): array { $id=$f['identifier'][0]??[];$a=$f['content'][0]['attachment']??[];$ctx=$f['context']['related'][0]['reference']??($f['context']['encounter'][0]['reference']??'');$localReport=(string)($f['extension'][0]['valueString']??$this->ref($ctx));return ['connection_key'=>'fhir','local_report_id'=>$localReport,'local_document_id'=>(string)($id['value']??$uuid??''),'external_identifier'=>['system'=>(string)($id['system']??'urn:neolims:document'),'value'=>(string)($id['value']??$uuid??'')],'filename'=>(string)($a['title']??('report-'.($id['value']??$uuid??'document').'.pdf')),'mimetype'=>(string)($a['contentType']??'application/pdf'),'content_base64'=>(string)($a['data']??''),'category_path'=>(string)($f['extension'][1]['valueString']??'/Lab Results'),'document_date'=>$this->fhirDate($f['date']??null)]; }
    private function normalize(array $r): array { foreach(['connection_key','local_report_id','local_document_id','filename','content_base64'] as $f)if(trim((string)($r[$f]??''))==='')throw new \InvalidArgumentException("$f is required.");$i=is_array($r['external_identifier']??null)?$r['external_identifier']:[];$filename=basename((string)$r['filename']);return ['connection_key'=>(string)$r['connection_key'],'local_report_id'=>(string)$r['local_report_id'],'local_document_id'=>(string)$r['local_document_id'],'identifier'=>['system'=>(string)($i['system']??'urn:neolims:document'),'value'=>(string)($i['value']??$r['local_document_id'])],'filename'=>$filename,'mimetype'=>(string)($r['mimetype']??'application/pdf'),'content_base64'=>(string)$r['content_base64'],'category_path'=>(string)($r['category_path']??'/Lab Results'),'document_date'=>(string)($r['document_date']??date('Y-m-d')),'max_bytes'=>(int)($r['max_bytes']??52428800)]; }
    private function ref(string $r): string{$p=explode('/',trim($r,'/'));return (string)end($p);} private function fhirDate($v): string{return $v?date('Y-m-d',strtotime((string)$v)):date('Y-m-d');}
}
