<?php
namespace OpenEMR\Modules\NeoLimsBridge\Service;
use OpenEMR\Modules\NeoLimsBridge\GlobalConfig;
use OpenEMR\Modules\NeoLimsBridge\Native\ProcedureResultWriter;
use OpenEMR\Modules\NeoLimsBridge\Repository\OrderLinkRepository;
use OpenEMR\Modules\NeoLimsBridge\Repository\ResultLinkRepository;
final class ProcedureResultSyncService
{
    private OrderLinkRepository $orders;private ResultLinkRepository $links;private GlobalConfig $config;
    public function __construct(){ $this->orders=new OrderLinkRepository();$this->links=new ResultLinkRepository();$this->config=new GlobalConfig($GLOBALS); }
    public function validate(array $r): array{$n=$this->normalize($r);$errors=[];$order=$this->orders->find($n['connection_key'],$n['local_order_id']);if(!$order&&$n['connection_key']==='hl7'){$matches=$this->orders->findByIdentifier('urn:neolims:order',$n['local_order_id']);$order=count($matches)===1?$matches[0]:null;}if(!$order)$errors[]='Permanent order link not found.';$seq=0;if($order){$row=sqlQuery('SELECT procedure_order_seq FROM procedure_order_code WHERE procedure_order_id=? AND procedure_code=? ORDER BY procedure_order_seq LIMIT 1',[(int)$order['openemr_order_id'],$n['report']['procedure_code']]);if($row)$seq=(int)$row['procedure_order_seq'];elseif($n['report']['procedure_order_seq']>0)$seq=$n['report']['procedure_order_seq'];else $errors[]='No matching order code sequence for the report.';}$n['report']['procedure_order_seq']=$seq;if($n['results']===[])$errors[]='At least one result is required.';foreach($n['results'] as $i=>$x){if($x['result_code']==='')$errors[]="results[$i].result_code is required.";}$existing=$this->links->find($n['connection_key'],$n['local_report_id']);$hash=hash('sha256',json_encode($n,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));return ['valid'=>$errors===[],'errors'=>$errors,'normalized'=>$n,'order_link'=>$order,'existing_result_link'=>$existing,'payload_hash'=>$hash,'can_create'=>$errors===[]&&!$existing];}
    public function sync(array $r): array{$v=$this->validate($r);if(!$v['valid'])return $v+['written'=>false];if($v['existing_result_link']&&hash_equals((string)$v['existing_result_link']['payload_hash'],$v['payload_hash']))return ['resolution'=>'unchanged','created'=>false,'written'=>false,'report'=>$this->links->getReport((int)$v['existing_result_link']['openemr_report_id'])];if(!empty($r['dry_run']))return $v+['written'=>false,'dry_run'=>true];if(!$this->config->enabled(GlobalConfig::ENABLE_NATIVE_WRITES))throw new \InvalidArgumentException('Native writes are disabled; use dry_run=true or enable the module setting.');$n=$v['normalized'];$previous=$v['existing_result_link'];if($previous&&in_array($previous['report_status'],['final','correct'],true)&&empty($r['allow_amendment']))throw new \InvalidArgumentException('Existing finalized report is immutable. Send allow_amendment=true and a new local_report_id/revision.');$revision=max(1,(int)($r['revision']??($previous?((int)$previous['revision']+1):1)));$created=(new ProcedureResultWriter())->create((int)$v['order_link']['openemr_order_id'],$n['report'],$n['results']);$this->links->save(['connection_key'=>$n['connection_key'],'local_report_id'=>$n['local_report_id'],'local_order_id'=>$n['local_order_id'],'openemr_report_uuid'=>$created['report_uuid'],'openemr_report_id'=>$created['report_id'],'openemr_order_id'=>(int)$v['order_link']['openemr_order_id'],'revision'=>$revision,'report_status'=>$n['report']['report_status'],'link_source'=>'created','external_identifier_system'=>$n['identifier']['system'],'external_identifier_value'=>$n['identifier']['value'],'payload_hash'=>$v['payload_hash']]);return ['resolution'=>'created','created'=>true,'written'=>true,'revision'=>$revision,'report'=>$this->links->getReport($created['report_id'])];}
    public function fromObservation(array $f,?string $uuid=null): array{$id=$f['identifier'][0]??[];$based=$this->ref($f['basedOn'][0]['reference']??'');$code=$f['code']['coding'][0]??[];$value=$f['valueQuantity']['value']??$f['valueString']??$f['valueCodeableConcept']['text']??'';$unit=$f['valueQuantity']['unit']??'';return ['connection_key'=>'fhir','local_order_id'=>$based,'local_report_id'=>(string)($f['extension'][0]['valueString']??('OBS-'.($id['value']??$uuid??''))),'external_identifier'=>['system'=>(string)($id['system']??'urn:neolims:observation'),'value'=>(string)($id['value']??$uuid??'')],'report'=>['procedure_code'=>(string)($f['extension'][1]['valueString']??$code['code']??''),'procedure_name'=>(string)($code['display']??$f['code']['text']??''),'date_collected'=>$this->fhirDate($f['effectiveDateTime']??null),'date_report'=>$this->fhirDate($f['issued']??null),'report_status'=>$this->fhirStatus((string)($f['status']??'final')),'report_notes'=>'','specimen_num'=>''],'results'=>[['result_data_type'=>is_numeric($value)?'N':'S','result_code'=>(string)($code['code']??''),'result_text'=>(string)($code['display']??$f['code']['text']??''),'date'=>$this->fhirDate($f['effectiveDateTime']??null),'facility'=>'','units'=>(string)$unit,'range'=>(string)($f['referenceRange'][0]['text']??''),'abnormal'=>$this->interpretation($f),'result_status'=>$this->fhirStatus((string)($f['status']??'final')),'result'=>(string)$value,'comments'=>(string)($f['note'][0]['text']??''),'document_id'=>null]]];}
    public function fromDiagnosticReport(array $f,?string $uuid=null): array{$id=$f['identifier'][0]??[];$based=$this->ref($f['basedOn'][0]['reference']??'');$code=$f['code']['coding'][0]??[];$results=[];foreach((array)($f['contained']??[]) as $obs){if(($obs['resourceType']??'')!=='Observation')continue;$results[]=$this->fromObservation($obs)['results'][0];}return ['connection_key'=>'fhir','local_order_id'=>$based,'local_report_id'=>(string)($id['value']??$uuid??''),'external_identifier'=>['system'=>(string)($id['system']??'urn:neolims:diagnostic-report'),'value'=>(string)($id['value']??$uuid??'')],'report'=>['procedure_code'=>(string)($code['code']??''),'procedure_name'=>(string)($code['display']??$f['code']['text']??''),'date_collected'=>$this->fhirDate($f['effectiveDateTime']??null),'date_report'=>$this->fhirDate($f['issued']??null),'report_status'=>$this->fhirStatus((string)($f['status']??'final')),'report_notes'=>(string)($f['conclusion']??''),'specimen_num'=>$this->ref($f['specimen'][0]['reference']??'')],'results'=>$results];}
    private function normalize(array $r): array{foreach(['connection_key','local_order_id','local_report_id'] as $f)if(trim((string)($r[$f]??''))==='')throw new \InvalidArgumentException("$f is required.");$rep=array_merge(['procedure_order_seq'=>0,'procedure_code'=>'','procedure_name'=>'','date_collected'=>date('Y-m-d H:i:s'),'date_collected_tz'=>'','date_report'=>date('Y-m-d H:i:s'),'date_report_tz'=>'','report_status'=>'prelim','report_notes'=>'','specimen_num'=>''],is_array($r['report']??null)?$r['report']:[]);$out=[];foreach((array)($r['results']??[]) as $x)$out[]=array_merge(['result_data_type'=>'S','result_code'=>'','result_text'=>'','date'=>$rep['date_report'],'facility'=>'','units'=>'','range'=>'','abnormal'=>'no','result_status'=>$rep['report_status'],'result'=>'','comments'=>'','document_id'=>null],is_array($x)?$x:[]);$i=is_array($r['external_identifier']??null)?$r['external_identifier']:[];return ['connection_key'=>(string)$r['connection_key'],'local_order_id'=>(string)$r['local_order_id'],'local_report_id'=>(string)$r['local_report_id'],'identifier'=>['system'=>(string)($i['system']??'urn:neolims:report'),'value'=>(string)($i['value']??$r['local_report_id'])],'report'=>$rep,'results'=>$out];}
    private function ref(string $r): string{$p=explode('/',trim($r,'/'));return (string)end($p);}private function fhirDate($v): string{return $v?date('Y-m-d H:i:s',strtotime((string)$v)):date('Y-m-d H:i:s');}private function fhirStatus(string $s): string{return match($s){'final'=>'final','amended','corrected'=>'correct','entered-in-error'=>'error',default=>'prelim'};}private function interpretation(array $f): string{$c=strtoupper((string)($f['interpretation'][0]['coding'][0]['code']??''));return match($c){'H'=>'high','L'=>'low','HH'=>'vhigh','LL'=>'vlow','A'=>'yes',default=>'no'};}
}
