<?php
namespace OpenEMR\Modules\NeoLimsBridge\Repository;
use OpenEMR\Common\Uuid\UuidRegistry;
final class ResultLinkRepository
{
    public function find(string $connection,string $local): ?array { $r=sqlQuery('SELECT * FROM neolims_bridge_result_link WHERE connection_key=? AND local_report_id=? LIMIT 1',[$connection,$local]); return $r?:null; }
    public function findByIdentifier(string $system,string $value): array { $s=sqlStatement('SELECT * FROM neolims_bridge_result_link WHERE external_identifier_system=? AND external_identifier_value=?',[$system,$value]);$rows=[];while($r=sqlFetchArray($s))$rows[]=$r;return $rows; }
    public function save(array $d): void { sqlStatement('INSERT INTO neolims_bridge_result_link (connection_key,local_report_id,local_order_id,openemr_report_uuid,openemr_report_id,openemr_order_id,revision,report_status,link_source,external_identifier_system,external_identifier_value,payload_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE openemr_report_uuid=VALUES(openemr_report_uuid),openemr_report_id=VALUES(openemr_report_id),openemr_order_id=VALUES(openemr_order_id),revision=VALUES(revision),report_status=VALUES(report_status),link_source=VALUES(link_source),external_identifier_system=VALUES(external_identifier_system),external_identifier_value=VALUES(external_identifier_value),payload_hash=VALUES(payload_hash),updated_at=NOW()',[$d['connection_key'],$d['local_report_id'],$d['local_order_id'],$d['openemr_report_uuid'],$d['openemr_report_id'],$d['openemr_order_id'],$d['revision'],$d['report_status'],$d['link_source'],$d['external_identifier_system'],$d['external_identifier_value'],$d['payload_hash']]); }
    public function getReport(int $id): ?array { $r=sqlQuery('SELECT pr.*,po.uuid order_uuid FROM procedure_report pr JOIN procedure_order po ON po.procedure_order_id=pr.procedure_order_id WHERE pr.procedure_report_id=?',[$id]);if(!$r)return null;if(!empty($r['uuid']))$r['uuid']=UuidRegistry::uuidToString($r['uuid']);if(!empty($r['order_uuid']))$r['order_uuid']=UuidRegistry::uuidToString($r['order_uuid']);$r['results']=[];$s=sqlStatement('SELECT * FROM procedure_result WHERE procedure_report_id=? ORDER BY procedure_result_id',[$id]);while($x=sqlFetchArray($s)){if(!empty($x['uuid']))$x['uuid']=UuidRegistry::uuidToString($x['uuid']);$r['results'][]=$x;}return $r; }
}
