CREATE TABLE IF NOT EXISTS `neolims_bridge_billing_link` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 `connection_key` VARCHAR(100) NOT NULL,
 `local_charge_id` VARCHAR(100) NOT NULL,
 `local_order_id` VARCHAR(100) NOT NULL DEFAULT '',
 `local_report_id` VARCHAR(100) NOT NULL DEFAULT '',
 `openemr_billing_id` BIGINT NOT NULL,
 `openemr_pid` BIGINT NOT NULL,
 `openemr_encounter_id` BIGINT NOT NULL,
 `code_type` VARCHAR(15) NOT NULL,
 `code` VARCHAR(20) NOT NULL,
 `modifier` VARCHAR(12) NOT NULL DEFAULT '',
 `units` INT NOT NULL DEFAULT 1,
 `fee` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
 `payload_hash` CHAR(64) NOT NULL,
 `link_source` VARCHAR(50) NOT NULL,
 `external_identifier_system` VARCHAR(255) NOT NULL DEFAULT '',
 `external_identifier_value` VARCHAR(255) NOT NULL DEFAULT '',
 `created_at` DATETIME NOT NULL,
 `updated_at` DATETIME NOT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `uq_neolims_billing_local` (`connection_key`,`local_charge_id`),
 UNIQUE KEY `uq_neolims_billing_openemr` (`openemr_billing_id`),
 KEY `idx_neolims_billing_external` (`external_identifier_system`(140),`external_identifier_value`(140))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
